WEATHER_TRANSLATIONS = {
    "thunderstorm with light rain": "Гроза с небольшим дождем",
    "thunderstorm with rain": "Гроза с дождем",
    "thunderstorm with heavy rain": "Гроза с сильным дождем",
    "light thunderstorm": "Слабая гроза",
    "thunderstorm": "Гроза",
    "heavy thunderstorm": "Сильная гроза",
    "ragged thunderstorm": "Порывистая гроза",
    "thunderstorm with light drizzle": "Гроза с небольшим моросящим дождем",
    "thunderstorm with drizzle": "Гроза с моросящим дождем",
    "thunderstorm with heavy drizzle": "Гроза с сильным моросящим дождем",
    "light intensity drizzle": "Слабый моросящий дождь",
    "drizzle": "Моросящий дождь",
    "heavy intensity drizzle": "Сильный моросящий дождь",
    "light rain": "Небольшой дождь",
    "moderate rain": "Умеренный дождь",
    "heavy intensity rain": "Сильный дождь",
    "very heavy rain": "Очень сильный дождь",
    "extreme rain": "Чрезвычайно сильный дождь",
    "freezing rain": "Ледяной дождь",
    "light snow": "Небольшой снег",
    "snow": "Снег",
    "heavy snow": "Сильный снегопад",
    "sleet": "Мокрый снег",
    "shower sleet": "Ливневый мокрый снег",
    "light rain and snow": "Небольшой дождь со снегом",
    "rain and snow": "Дождь со снегом",
    "light shower snow": "Небольшой ливневый снег",
    "shower snow": "Ливневый снег",
    "heavy shower snow": "Сильный ливневый снег",
    "mist": "Туман",
    "smoke": "Дымка",
    "haze": "Мгла",
    "sand/dust whirls": "Пыльные вихри",
    "fog": "Густой туман",
    "clear sky": "Ясное небо",
    "few clouds": "Малооблачно",
    "scattered clouds": "Рассеянные облака",
    "broken clouds": "Облачность",
    "overcast clouds": "Пасмурно",
    "tornado": "Торнадо",
    "tropical storm": "Тропический шторм",
    "hurricane": "Ураган",
    "cold": "Холодно",
    "hot": "Жарко",
    "windy": "Ветрено",
    "hail": "Град",
}

def translate_weather(description):
    return WEATHER_TRANSLATIONS.get(
        description,
        "Неизвестное погодное явление"
    )